config/routes.rb
Marketplace::Application.routes.draw do
  resources :product_categories
  resources :product_stock_sizes
  resources :store_statuses
  
  get 'products' => 'products#index', as: 'products'
  resources :stores do 
    resources :products    
  end
  
  get "welcome/index"
  
  post 'set_time_zone' => 'application#set_time_zone', as: 'set_time_zone'
    
  devise_for :users
  

  root 'welcome#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :products
  
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/x-png', 'image/pjpeg']
	validates_attachment_size :logo, :less_than => 2.megabytes

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :logo)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :logo %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/index.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:logo_file_name) %></th>
      <th><%= model_class.human_attribute_name(:logo_content_type) %></th>
      <th><%= model_class.human_attribute_name(:logo_file_size) %></th>
      <th><%= model_class.human_attribute_name(:logo_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:store_status_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.id, store_path(store) %></td>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.logo_file_name %></td>
        <td><%= store.logo_content_type %></td>
        <td><%= store.logo_file_size %></td>
        <td><%= store.logo_updated_at %></td>
        <td><%= store.store_status_id %></td>
        <td><%=l store.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_path(store), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_path(store),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_store_path,
            :class => 'btn btn-primary' %>

app/views/stores/new.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/show.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%= @store.name %></h1>
</div>
<%= image_tag @store.logo.url(:medium) %>
<p><%= @store.address %></p>
<p>Status: <%= @store.store_status_id %></p>
<div class="page-header">
  <h1>Categorías en las que participa</h1>
</div>
<p>Las categorías se agregan automáticamente en función de las categorías de los productos que se seleccionen</p>
<div class="page-header">
  <h1>Productos</h1>
  <%= link_to 'Nuevo Producto', new_store_product_path(@store) %>
</div>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_path(@store), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_path(@store),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>