config/routes.rb
Marketplace::Application.routes.draw do
  resources :product_categories
  resources :product_stock_sizes
  resources :store_statuses
  
  get 'products' => 'products#index', as: 'products'
  resources :stores do 
    resources :products    
  end
  
  get "welcome/index"
  
  post 'set_time_zone' => 'application#set_time_zone', as: 'set_time_zone'
    
  devise_for :users
  

  root 'welcome#index'

end

app/controllers/store_statuses_controller.rb
class StoreStatusesController < ApplicationController
  before_action :set_store_status, only: [:show, :edit, :update, :destroy]

  # GET /store_statuses
  # GET /store_statuses.json
  def index
    @store_statuses = StoreStatus.all
  end

  # GET /store_statuses/1
  # GET /store_statuses/1.json
  def show
  end

  # GET /store_statuses/new
  def new
    @store_status = StoreStatus.new
  end

  # GET /store_statuses/1/edit
  def edit
  end

  # POST /store_statuses
  # POST /store_statuses.json
  def create
    @store_status = StoreStatus.new(store_status_params)

    respond_to do |format|
      if @store_status.save
        format.html { redirect_to @store_status, notice: 'Store status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @store_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_statuses/1
  # PATCH/PUT /store_statuses/1.json
  def update
    respond_to do |format|
      if @store_status.update(store_status_params)
        format.html { redirect_to @store_status, notice: 'Store status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_statuses/1
  # DELETE /store_statuses/1.json
  def destroy
    @store_status.destroy
    respond_to do |format|
      format.html { redirect_to store_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_status
      @store_status = StoreStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_status_params
      params.require(:store_status).permit(:name, :description)
    end
end

app/helpers/store_statuses_helper.rb
module StoreStatusesHelper
end

app/views/store_statuses/_form.html.erb
<%= form_for(@store_status) do |f| %>
  <% if @store_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store_status.errors.count, "error") %> prohibited this store_status from being saved:</h2>

      <ul>
      <% @store_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/store_statuses/edit.html.erb
<h1>Editing store_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @store_status %> |
<%= link_to 'Back', store_statuses_path %>

app/views/store_statuses/index.html.erb
<h1>Listing store_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @store_statuses.each do |store_status| %>
      <tr>
        <td><%= store_status.name %></td>
        <td><%= store_status.description %></td>
        <td><%= link_to 'Show', store_status %></td>
        <td><%= link_to 'Edit', edit_store_status_path(store_status) %></td>
        <td><%= link_to 'Destroy', store_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store status', new_store_status_path %>

app/views/store_statuses/new.html.erb
<h1>New store_status</h1>

<%= render 'form' %>

<%= link_to 'Back', store_statuses_path %>

app/views/store_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store_status.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store_status.description %>
</p>

<%= link_to 'Edit', edit_store_status_path(@store_status) %> |
<%= link_to 'Back', store_statuses_path %>