config/routes.rb
Marketplace::Application.routes.draw do
  resources :product_categories
  resources :product_stock_sizes
  resources :store_statuses
  
  get 'products' => 'products#index', as: 'products'
  resources :stores do 
    resources :products    
  end
  
  get "welcome/index"
  
  post 'set_time_zone' => 'application#set_time_zone', as: 'set_time_zone'
    
  devise_for :users
  

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :store
  has_many :product_images
  has_and_belongs_to_many :product_categories
  has_many :product_stock_sizes
  
  accepts_nested_attributes_for :product_images, :allow_destroy => true
	accepts_nested_attributes_for :product_stock_sizes, :allow_destroy => true
	
  validates :name, presence: true, :uniqueness => {:scope => :store_id}
  validates :price, presence: true
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_store, except: [:index]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.js  { render :json => @product, :callback => params[:callback] }
      format.json  { render :json => @product }
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    puts product_params
    respond_to do |format|
      if @product.save
        format.html { redirect_to [@store, @product], notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@store, @product] }
      else
        format.html { render action: 'new' }
        format.json { render json: [@store, @product].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@store, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [@store, @product].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to store_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
    def set_store
      @store = Store.find(params[:store_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :store_id, product_category_ids: [], product_images_attributes: [:id, :photo, :_destroy], product_stock_sizes_attributes: [:id, :stock, :size, :color, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= nested_form_for [@store, @product], :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'layouts/form_errors', object: @product %>
	<%= f.hidden_field :store_id, :value => @store.id %>
	<div class="control-group">
	  <%= f.label :name, :class => 'control-label' %>
	  <div class="controls">
	    <%= f.text_field :name, :class => 'text_field' %>
	  </div>
	</div>
	<div class="control-group">
	  <%= f.label :description, :class => 'control-label' %>
	  <div class="controls">
	    <%= f.text_area :description, :class => 'text_field' %>
	  </div>
	</div>
	<div class="control-group">
	  <%= f.label :price, :class => 'control-label' %>
	  <div class="controls">
	    <%= f.text_field :price, :class => 'text_field' %>
	  </div>
	</div>
	<h2>Categorías</h2>
		<%= render 'product_categories', :f => f %>
	<h2>Modelos</h2>
	<p style="margin-top:-20px">Importante: <b>nunca elimines una talla/color</b></p>
		<%= render 'product_stock_size_fields', :f => f %>
	<h2>Imágenes</h2>
		<%= render 'product_image_fields', :f => f %>	

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                store_products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/_product_categories.html.erb
<div class="control-group">
	  <div class="controls">
<% ProductCategory.all.each_with_index do |pc, i| %>
	<label class="checkbox inline">
	  <%= check_box_tag("product[product_category_ids][]", pc.id, (@product.product_categories.include? pc)) %> <%= pc.name.capitalize %>
	</label>
<% end %>
	</div>
</div>

app/views/products/_product_image_fields.html.erb
<%= f.fields_for :product_images do |image| %>
<div class="control-group">
	<div class="controls">
		<%= image_tag image.object.photo.url(:tiny) %>
		<%= image.file_field :photo %>
		<%= image.link_to_remove 'Eliminar', :class => 'btn btn-default btn-mini' %>
	</div>
</div>
<% end %>

<div>
<%= f.link_to_add 'Agregar Imagen', :product_images, :class => 'btn btn-primary btn-mini' %>
</div>

app/views/products/_product_stock_size_fields.html.erb
<%= f.fields_for :product_stock_sizes do |pdz| %>
<div class="control-group">
	<div class="controls">
		<%= pdz.text_field :stock, placeholder: 'Stock' %>
		<%= pdz.text_field :size, placeholder: 'Talla', :disabled => (pdz.object.id.blank? ? false : true) %>
		<%= pdz.text_field :color, placeholder: 'Color', :disabled => (pdz.object.id.blank? ? false : true) %>
		<%= pdz.link_to_remove 'Eliminar', :class => 'btn btn-default btn-mini' %>
	</div>
</div>
<% end %>

<div>
	<%= f.link_to_add 'Agregar Talla/Color', :product_stock_sizes, :class => 'btn btn-primary btn-mini' %>
</div>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, store_product_path(id: product.id, store_id: product.store.id) %></td>
        <td><%= product.store.name %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_product_path(id: product.id, store_id: product.store.id), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_product_path(id: product.id, store_id: product.store.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:store_id) %>:</strong></dt>
  <dd><%= @product.store_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>
<h2>Categorías</h2>
<div class="well">
	<% if @product.product_categories.size > 0 %>
		<% @product.product_categories.each do |pc| %>
			<span class="label"><%= pc.name %></span>
		<% end %>
	<% else %>
		Este producto no tiene categorías asociadas
	<% end %>
</div>
<h2>Tallas y Modelos</h2>
<div class="well">
<% if @product.product_stock_sizes.size > 0 %>
<ul>
	<% @product.product_stock_sizes.each do |psz| %>
		<li><%= psz.stock %> - <%= psz.size %> - <%= psz.color %></li>
	<% end %>
</ul>
<% else %>
	No se han agregado las tallas a este producto
<% end %>
</div>
<h2>Imágenes</h2>
<div class="well">
<% if @product.product_images.size > 0 %>
	<% @product.product_images.each do |product_image| %>
		<%= image_tag product_image.photo.url(:medium) %>
	<% end %>
<% else %>
	No se han agregado imágenes para este producto
<% end %>
</div>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              store_products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_product_path, :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_product_path,
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>