config/routes.rb
Marketplace::Application.routes.draw do
  resources :product_categories
  resources :product_stock_sizes
  resources :store_statuses
  
  get 'products' => 'products#index', as: 'products'
  resources :stores do 
    resources :products    
  end
  
  get "welcome/index"
  
  post 'set_time_zone' => 'application#set_time_zone', as: 'set_time_zone'
    
  devise_for :users
  

  root 'welcome#index'

end

app/views/layouts/_date_range_selector.html.erb
<%= form_tag(request.fullpath, :method => "get", :html => {class: 'form-inline'}) do %>
	<div class="input-prepend">
	  <span class="add-on">Desde</span>
		<%= text_field_tag(:from, @from.strftime("%Y-%m-%d"), class: 'datepicker') %>
	</div>
	<div class="input-prepend">
	  	<span class="add-on">Hasta</span>
		<%= text_field_tag(:to, @to.strftime("%Y-%m-%d"), class: 'datepicker') %>
	</div>
	<%= submit_tag("Actualizar",  class: "btn", style: 'vertical-align:top') %>
<% end %>

app/views/layouts/_email.html.erb
<table width="100%" style="font-size:12px;" cellpadding="0" cellspacing="0">
	<tr id="content">
		<td>
			<%= yield :content %>
		</td>
	</tr>
	<tr id="copyright">
		<td align="right">
			<span style="font-family: 'Lucida Grande', 'Segoe UI', Arial, Verdana, 'Lucida Sans Unicode', Tahoma, 'Sans Serif'; font-size: 11px; color: #888;">&copy;&nbsp;<%= Date.today.year %>&nbsp; <a href="www.inventariolibre.com">InventarioLibre.com</a></span>
		</td>
	</tr>
</table>

app/views/layouts/_footer.html.erb
<hr>
<footer>
  <p>InventarioLibre.com &copy; 2014 | Zona horaria <%= cookies[:time_zone] %> | <%= link_to '¿Tienes una tienda?', new_store_path %></p>
</footer>

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&#215;</a>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_top_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
  		<%= link_to 'Logo', '#', class: 'brand' %>	 
		<ul class="nav navbar-nav"> 
			<li class="active"><%= link_to 'Tiendas', stores_path %></li>
			<li class=""><%= link_to 'Productos', products_path %></li>
		</ul>
		<% if user_signed_in? %>
		<ul class="nav navbar-nav navbar-right pull-right">
        	<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100" data-close-others="true">Tu Cuenta <b class="caret"></b></a>
	          <ul class="dropdown-menu">
				<li><%= link_to 'Administrar Tiendas', '#' %></li>
				<li><%= link_to 'Cambiar clave', '#' %></li>
				<li role="presentation" class="divider"></li>
				<li><%= link_to 'Salir de '+current_user.email, destroy_user_session_path, method: :delete, :rel => 'nofollow' %></li>
	          </ul>
	        </li>
      	</ul>
	  	<% else %>
			<ul class="nav navbar-nav navbar-right pull-right">
				<li><%= link_to 'Entrar', new_session_path(resource_name) %></li>
				<li><%= link_to 'Registrase', new_user_registration_path %></li>
			</ul>
	 	<% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MarketPlace" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

	<script src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js" type="text/javascript"></script>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
	<%= render 'layouts/top_menu' %>
    <div class="container">
        <div class="row">
          <div class="span12">
			<%= render_breadcrumbs %>
            <%= bootstrap_flash %>
           	<%= yield %>
          </div>
        </div><!--/row-->
		<%= render 'layouts/footer' %>
    </div> <!-- /container -->

  </body>
</html>